version: '3.8'
services:
  node-server:
    image: node:16-alpine
    container_name: node-server
    ports:
      - "3000:3000"
    volumes:
      - "./:/app"
    working_dir: "/app"
    command:
      - /bin/sh
      - -c
      - |
        npm i
        npm run start-node-dev

  add-header-server:
    image: node:16-alpine
    container_name: add-header-server
    ports:
      - "3001:3001"
    volumes:
      - "./:/app"
    working_dir: "/app"
    command:
      - /bin/sh
      - -c
      - |
        npm i
        npm run start-add-header-dev
